In [1]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [2]:
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

M_data = [[1., 2., 3.], [4., 5., 6.]]
M = torch.tensor(M_data)
print(M)

T_data = [[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([ 1.,  2.,  3.])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]]])


In [3]:
print(V[0])
print(V[0].item())
print(M[0])
print(T[0])

tensor(1.)
1.0
tensor([ 1.,  2.,  3.])
tensor([[ 1.,  2.],
        [ 3.,  4.]])


In [4]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])


In [5]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([ 5.,  7.,  9.])


In [6]:
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

x_2 = torch.rand(2, 3)
y_2 = torch.rand(2, 5)
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

tensor([[-0.8029,  0.2366,  0.2857,  0.6898, -0.6331],
        [ 0.8795, -0.6842,  0.4533,  0.2912, -0.8317],
        [-0.5525,  0.6355, -0.3968, -0.6571, -1.6428],
        [ 0.9803, -0.0421, -0.8206,  0.3133, -1.1352],
        [ 0.3773, -0.2824, -2.5667, -1.4303,  0.5009]])
tensor([[ 0.7881,  0.9642,  0.1895,  0.8116,  0.8553,  0.8163,  0.6291,
          0.1581],
        [ 0.6085,  0.9314,  0.8313,  0.0801,  0.2709,  0.4418,  0.1935,
          0.6829]])


In [7]:
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))
print(x.view(2, -1))

tensor([[[-1.3633, -0.9832,  1.5113,  0.6419],
         [ 0.4730, -0.4286,  0.5514, -1.5474],
         [ 0.2505, -0.7930,  0.5231,  1.2236]],

        [[-0.9458, -1.3529,  3.3837, -2.4044],
         [-0.3891, -0.0796,  0.7605, -1.0025],
         [ 0.9462,  0.3512,  1.5728,  1.7185]]])
tensor([[-1.3633, -0.9832,  1.5113,  0.6419,  0.4730, -0.4286,  0.5514,
         -1.5474,  0.2505, -0.7930,  0.5231,  1.2236],
        [-0.9458, -1.3529,  3.3837, -2.4044, -0.3891, -0.0796,  0.7605,
         -1.0025,  0.9462,  0.3512,  1.5728,  1.7185]])
tensor([[-1.3633, -0.9832,  1.5113,  0.6419,  0.4730, -0.4286,  0.5514,
         -1.5474,  0.2505, -0.7930,  0.5231,  1.2236],
        [-0.9458, -1.3529,  3.3837, -2.4044, -0.3891, -0.0796,  0.7605,
         -1.0025,  0.9462,  0.3512,  1.5728,  1.7185]])


In [8]:
x = torch.tensor([1., 2., 3.], requires_grad=True)

y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x + y
print(z)

print(z.grad_fn)

tensor([ 5.,  7.,  9.])


In [9]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21.)


In [10]:
s.backward()
print(x.grad)

tensor([ 1.,  1.,  1.])


In [11]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
print(z.grad_fn)

x.requires_grad_()
y.requires_grad_()
z = x + y
print(z.grad_fn)
print(z.requires_grad)

new_z = z.detach()

print(new_z.grad_fn)

False False
None
True
None


In [12]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
