In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

# print(x[1][0])

tensor([[ 0.0000e+00, -2.0000e+00,  0.0000e+00],
        [-2.0000e+00,  1.2564e-34,  1.4013e-45],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 2.8026e-45,  0.0000e+00, -2.1164e+33]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.3995,  0.9964,  0.5851],
        [ 0.5523,  0.2569,  0.3518],
        [ 0.5280,  0.7810,  0.8321],
        [ 0.2115,  0.5589,  0.4090],
        [ 0.2388,  0.4543,  0.5861]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.4852,  0.3681,  0.6996],
        [-0.3659, -0.1760,  0.0735],
        [-0.3290,  1.2999, -2.3124],
        [ 0.7588,  0.2331, -1.2046],
        [-1.6112, -0.1231, -2.2406]])


In [7]:
print(x.size())

# print(x.size()[0])

torch.Size([5, 3])


In [8]:
x = torch.rand(5, 3)
print(x)

y = torch.rand(5, 3)
print(y)

tensor([[ 0.3135,  0.0961,  0.6806],
        [ 0.9388,  0.5441,  0.0377],
        [ 0.6244,  0.1607,  0.9788],
        [ 0.1138,  0.3191,  0.2073],
        [ 0.2748,  0.7080,  0.4251]])
tensor([[ 0.2468,  0.8831,  0.4970],
        [ 0.0370,  0.4938,  0.7023],
        [ 0.9077,  0.2264,  0.7118],
        [ 0.5011,  0.2658,  0.4620],
        [ 0.4445,  0.2637,  0.2480]])


In [9]:
print(x + y)

tensor([[ 0.5604,  0.9792,  1.1776],
        [ 0.9757,  1.0379,  0.7400],
        [ 1.5321,  0.3871,  1.6906],
        [ 0.6149,  0.5849,  0.6693],
        [ 0.7194,  0.9717,  0.6731]])


In [10]:
print(torch.add(x, y))

tensor([[ 0.5604,  0.9792,  1.1776],
        [ 0.9757,  1.0379,  0.7400],
        [ 1.5321,  0.3871,  1.6906],
        [ 0.6149,  0.5849,  0.6693],
        [ 0.7194,  0.9717,  0.6731]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5604,  0.9792,  1.1776],
        [ 0.9757,  1.0379,  0.7400],
        [ 1.5321,  0.3871,  1.6906],
        [ 0.6149,  0.5849,  0.6693],
        [ 0.7194,  0.9717,  0.6731]])


In [12]:
print(y)
y.add_(x)
print(y)

tensor([[ 0.2468,  0.8831,  0.4970],
        [ 0.0370,  0.4938,  0.7023],
        [ 0.9077,  0.2264,  0.7118],
        [ 0.5011,  0.2658,  0.4620],
        [ 0.4445,  0.2637,  0.2480]])
tensor([[ 0.5604,  0.9792,  1.1776],
        [ 0.9757,  1.0379,  0.7400],
        [ 1.5321,  0.3871,  1.6906],
        [ 0.6149,  0.5849,  0.6693],
        [ 0.7194,  0.9717,  0.6731]])


In [13]:
print(x)
print(x[:, 1])

tensor([[ 0.3135,  0.0961,  0.6806],
        [ 0.9388,  0.5441,  0.0377],
        [ 0.6244,  0.1607,  0.9788],
        [ 0.1138,  0.3191,  0.2073],
        [ 0.2748,  0.7080,  0.4251]])
tensor([ 0.0961,  0.5441,  0.1607,  0.3191,  0.7080])


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor(1.00000e-02 *
       [ 2.1734])
0.021733770147


In [16]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [20]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))